#!/bin/bash
set -euo pipefail

# Fuzz the hostile-input paths. The host half: build the image if it is not there, then
# hand the arguments to build-inside.sh.
#
#   docker/fuzz/fuzz.sh build
#   docker/fuzz/fuzz.sh run archive 1800
#   docker/fuzz/fuzz.sh run content 900
#   docker/fuzz/fuzz.sh replay
#   docker/fuzz/fuzz.sh minimise archive
#   docker/fuzz/fuzz.sh coverage archive
#
# The repository is mounted READ-ONLY and that is not tidiness. A fuzzer writes its
# corpus to disk and writes a new file for every input it minimises; pointed at a
# directory inside a tree somebody pushes, it grows one nobody is watching. Everything
# it writes goes to fuzz/work/, which .gitignore names.
#
# Nothing from trail-data/, corpus/local/ or corpus/blobs/ may ever be used as a seed,
# for the same reason: a seed taken from held material would be copied, mutated and
# minimised into hundreds of files. fuzz/seeds/ is synthetic and generated by
# fuzz/make-seeds.py, which reads nothing.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
WORK_DIR="${LYXBOSA_FUZZ_WORK:-${PROJECT_ROOT}/fuzz/work}"
IMAGE=lyxbosa-fuzz
# The build tree and the working directory are both overridable, and the reason is the
# control rather than convenience. Proving this rig can report a defect means building a
# tree with a defect planted in it, and that build must not land on top of the one a
# campaign is running out of. AGENTS.md says a harness that mutates tracked files works on
# a copy; a harness that replaces a running binary wants its own volume for the same
# reason.
VOLUME="${LYXBOSA_FUZZ_VOLUME:-lyxbosa-fuzz-build}"

[ $# -gt 0 ] || { echo "usage: $0 <build|run|replay|minimise|coverage|shell> [args...]" >&2; exit 2; }

if [ -z "$(docker images -q "${IMAGE}" 2>/dev/null)" ] || [ "${LYXBOSA_FUZZ_REBUILD:-0}" = "1" ]; then
    echo "=== building ${IMAGE} (clang, sanitizers, vcpkg deps: slow the first time) ==="
    docker build -t "${IMAGE}" -f "${SCRIPT_DIR}/Dockerfile" "${PROJECT_ROOT}"
fi

mkdir -p "${WORK_DIR}"

# The container runs as the invoking user, not as root.
#
# Everything it produces - the corpus, the crashing inputs, the coverage reports - lands
# in fuzz/work/ on the host, and a campaign whose output is owned by root is a campaign
# whose findings cannot be opened, moved or deleted without sudo. docker/build/Linux does
# run as root and its CI job has a "Reclaim cache ownership" step to undo it; not needing
# the step is better than having one. The build volume is chowned once, when it is
# created, because a fresh docker volume belongs to root.
UID_GID="$(id -u):$(id -g)"
if ! docker volume inspect "${VOLUME}" >/dev/null 2>&1; then
    docker volume create "${VOLUME}" >/dev/null
    docker run --rm -v "${VOLUME}:/builds" --entrypoint chown "${IMAGE}" -R "${UID_GID}" /builds
fi

# --tty only when there is one, so this works the same from a script.
TTY_FLAGS=()
[ -t 0 ] && TTY_FLAGS=(-it)

exec docker run --rm "${TTY_FLAGS[@]}" \
    -u "${UID_GID}" \
    -e HOME=/tmp \
    -v "${PROJECT_ROOT}:/src:ro" \
    -v "${WORK_DIR}:/work" \
    -v "${VOLUME}:/builds" \
    "${IMAGE}" "$@"
